name: flutter_portfolio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  photo_view: ^0.14.0
  url_launcher: ^6.1.12
  font_awesome_flutter: ^10.5.0
  carousel_slider: ^5.0.0
  nb_utils: ^4.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

 #body fonts
  # fonts: 
  #   - family: Poppins
  #     fonts: 
  #       - asset: fonts/PoppinsRegular.ttf
        
    # #handing fonts
    # - family: futurbci
    #   fonts: 
    #     - asset: fonts/futurbci.ttf